server:
  port: 9999
spring:
  application:
    name: admin-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
