server:
  port: 8081
spring:
  application:
    name: service-tes
  boot:
    admin:
      client:
        url: http://localhost:9999
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 #表示eureka client发送心跳给server端的频率，默认为30秒
    health-check-url-path: /actuator/health #健康检查的地址（依赖spring-boot-starter-actuator）
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


