eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 4444
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /admin/**
      serviceId: service-feign
    cart:
      path: /cart/**
      serviceId: service-spcart
  add-host-header: true
  sensitive-headers:

